# Generated by Django 2.0.6 on 2019-07-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('gender', models.CharField(default='', max_length=255, null=True)),
                ('image', models.CharField(default='', max_length=255, null=True)),
                ('otp', models.CharField(default='', max_length=255, null=True)),
                ('otp_time', models.CharField(default='', max_length=255, null=True)),
                ('verify_link', models.CharField(default='', max_length=255, null=True)),
                ('login_time', models.CharField(default='', max_length=255, null=True)),
                ('active', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='roledetails',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpanel.UserRole'),
        ),
    ]
